[options] --msgid-bugs-address jafesp@gmail.com

[options] --copyright-holder "Jamenson Ferreira Espindula de Almeida Melo"

[options] --package-name Texinfo

[options] --package-version "future release"

[options] --keep 0

[po4a_langs] pt_BR

[po4a_paths] texinfo/phase_1/po/$master.pot pt_BR:texinfo/phase_1/po/$master.$lang.po

### Documentos a serem traduzidos
### Tipo do documento   Documento original   Documento traduzido

[type: texinfo] texinfo/phase_1/upstream/texinfo.texi pt_BR:texinfo/phase_1/translated/texinfo.$lang.texi

#[type: texinfo] texinfo/phase_1/upstream/pod2texi.texi pt_BR:texinfo/phase_1/translated/pod2texi.$lang.texi
