[options] --msgid-bugs-address jafesp@gmail.com

[options] --copyright-holder "Jamenson Ferreira Espindula de Almeida Melo"

[options] --package-name Texinfo

[options] --package-version 7.1

[po_directory] texinfo/po4a/

[type: texinfo] texinfo/texinfo-ed.7.1-en_US.texi $lang:texinfo/translated/texinfo-ed.7.1-$lang.texi
