[options] --msgid-bugs-address jafesp@gmail.com

[options] --copyright-holder "Jamenson Ferreira Espindula de Almeida Melo"

[options] --package-name Texinfo

[options] --package-version 7.3

[options] --keep 0

[po4a_langs] pt_BR

[po4a_paths] texinfo/gettextized/$master.pot pt_BR:texinfo/gettextized/$master.$lang.po

### Documentos a serem traduzidos
### Tipo do documento   Documento original   Documento traduzido

[type: texinfo] texinfo/upstream/texinfo.texi pt_BR:texinfo/translated/texinfo.$lang.texi

#[type: texinfo] texinfo/upstream/pod2texi.texi pt_BR:texinfo/translated/pod2texi.$lang.texi
